# Generated by Django 2.1.2 on 2018-10-31 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната чата', 'verbose_name_plural': 'Комнаты чатов'},
        ),
    ]
